routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\MainController;
use App\Http\Controllers\HRM\UserController;
use App\Http\Controllers\RegionalController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\CRM\ClientController;
use App\Http\Controllers\CRM\SupplierController;
use App\Http\Controllers\Master\ProductController;
use App\Http\Controllers\Finance\AccountController;
use App\Http\Controllers\Finance\CashFlowController;
use App\Http\Controllers\Transaction\SaleController;
use App\Http\Controllers\Master\ProductUnitController;
use App\Http\Controllers\Finance\AccountTypeController;
use App\Http\Controllers\Transaction\ExpenseController;
use App\Http\Controllers\Finance\BalanceSheetController;
use App\Http\Controllers\Transaction\PurchaseController;
use App\Http\Controllers\Master\ProductCategoryController;
use App\Http\Controllers\Transaction\SaleDetailController;
use App\Http\Controllers\Finance\IncomeStatementController;
use App\Http\Controllers\Master\ProductVariationController;
use App\Http\Controllers\Transaction\SalePaymentController;
use App\Http\Controllers\Transaction\ExpensePaymentController;
use App\Http\Controllers\Transaction\PurchaseDetailController;
use App\Http\Controllers\Transaction\ExpenseCategoryController;
use App\Http\Controllers\Transaction\PurchasePaymentController;

Route::name('app.')->group(function(){
    Route::prefix('auth')->name('auth.')->group(function(){
        Route::get('',[AuthController::class, 'index'])->name('index');
        Route::post('login',[AuthController::class, 'do_login'])->name('login');
    });
    
    Route::middleware(['auth:web'])->group(function(){
        Route::redirect('/', 'dashboard', 301);
        Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
        Route::get('report', [DashboardController::class, 'report'])->name('report');
        Route::get('keuangan', [DashboardController::class, 'keuangan'])->name('keuangan');
        Route::get('data-data', [MainController::class, 'data'])->name('data');
        Route::resource('product-category', ProductCategoryController::class);
        Route::resource('product-unit', ProductUnitController::class);
        Route::resource('product', ProductController::class);
        Route::post('product/get', [ProductController::class, 'get'])->name('product.get');
        Route::post('product/get_list', [ProductController::class, 'get_list'])->name('product.get_list');
        Route::get('product/{product}/timbang', [ProductController::class, 'timbang'])->name('product.timbang');
        Route::post('product/timbang/store', [ProductController::class, 'timbang_store'])->name('product.timbang.store');
        Route::resource('product-variation', ProductVariationController::class);
        Route::post('product-variation/get_list', [ProductVariationController::class, 'get_list'])->name('product-variation.get_list');
        Route::resource('supplier', SupplierController::class);
        Route::post('supplier/get', [SupplierController::class, 'get'])->name('supplier.get');
        Route::post('supplier/get_list', [SupplierController::class, 'get_list'])->name('supplier.get_list');
        Route::resource('client', ClientController::class);
        Route::post('client/get', [ClientController::class, 'get'])->name('client.get');
        Route::post('client/get_list', [ClientController::class, 'get_list'])->name('client.get_list');
        Route::resource('user', UserController::class);
        Route::resource('account-type', AccountTypeController::class);
        Route::resource('account', AccountController::class);
        Route::resource('purchase', PurchaseController::class);
        Route::resource('purchase-detail', PurchaseDetailController::class);
        Route::resource('purchase-payment', PurchasePaymentController::class);
        Route::post('purchase/{purchase}/process', [PurchaseController::class, 'process'])->name('purchase.process');
        Route::post('purchase/{purchase}/finish', [PurchaseController::class, 'finish'])->name('purchase.finish');
        Route::resource('sale', SaleController::class);
        Route::resource('sale-detail', SaleDetailController::class);
        Route::resource('sale-payment', SalePaymentController::class);
        Route::get('cash-flow', [CashFlowController::class, 'index'])->name('cash-flow.index');
        Route::get('income-statement', [IncomeStatementController::class, 'index'])->name('income-statement.index');
        Route::get('balance-sheet', [BalanceSheetController::class, 'index'])->name('balance-sheet.index');
        Route::post('sale/{sale}/process', [SaleController::class, 'process'])->name('sale.process');
        Route::post('sale/{sale}/finish', [SaleController::class, 'finish'])->name('sale.finish');
        Route::resource('expense-category', ExpenseCategoryController::class);
        Route::get('expense/{expense}/journal', [ExpenseController::class, 'journal'])->name('expense.journal');
        Route::resource('expense', ExpenseController::class);
        Route::resource('expense-payment', ExpensePaymentController::class);
        Route::post('city/get_city', [RegionalController::class, 'get_city'])->name('regional.get_city');
        Route::post('subdistrict/get_subdistrict', [RegionalController::class, 'get_subdistrict'])->name('regional.get_subdistrict');
        Route::get('logout',[AuthController::class, 'do_logout'])->name('auth.logout');
    });
});

app/Http/Controllers/MainController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class MainController extends Controller
{
    public function index(){
        
    }
    public function data()
    {
        return view('page.main.data');
    }
}

resources/views/page/main/data.blade.php
<x-app-layout title="Selamat datang">
    <div class="container-xxl" id="kt_content_container">
        <div class="card-p position-relative">
            <!--begin::Row-->
            <div class="row g-0">
                <!--begin::Col-->
                <div class="col px-4 py-8 rounded-2 me-7 btn btn-hover-rise mb-7" style="background-color: #2EB3EC;">
                    <a href="{{route('app.client.index')}}" class="text-warning fw-bold fs-6">
                        <div class="row g-0">
                            <div class="col px-6 py-8 text-center">
                                <span class="svg-icon svg-icon-light svg-icon-4hx"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                <path d="M16.0173 9H15.3945C14.2833 9 13.263 9.61425 12.7431 10.5963L12.154 11.7091C12.0645 11.8781 12.1072 12.0868 12.2559 12.2071L12.6402 12.5183C13.2631 13.0225 13.7556 13.6691 14.0764 14.4035L14.2321 14.7601C14.2957 14.9058 14.4396 15 14.5987 15H18.6747C19.7297 15 20.4057 13.8774 19.912 12.945L18.6686 10.5963C18.1487 9.61425 17.1285 9 16.0173 9Z" fill="currentColor"/>
                                <rect opacity="0.3" x="14" y="4" width="4" height="4" rx="2" fill="currentColor"/>
                                <path d="M4.65486 14.8559C5.40389 13.1224 7.11161 12 9 12C10.8884 12 12.5961 13.1224 13.3451 14.8559L14.793 18.2067C15.3636 19.5271 14.3955 21 12.9571 21H5.04292C3.60453 21 2.63644 19.5271 3.20698 18.2067L4.65486 14.8559Z" fill="currentColor"/>
                                <rect opacity="0.3" x="6" y="5" width="6" height="6" rx="3" fill="currentColor"/>
                                </svg></span>
                                <p class="fs-1 pt-2 text-white">Pelanggan</p>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col px-4 py-8 rounded-2 me-7 btn btn-hover-rise mb-7" style="background-color: #54B857;">
                    <a href="{{route('app.supplier.index')}}" class="text-warning fw-bold fs-6">
                        <div class="row g-0">
                            <div class="col px-6 py-8 text-center">
                                <span class="svg-icon svg-icon-light svg-icon-4hx"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                <path d="M20 14H18V10H20C20.6 10 21 10.4 21 11V13C21 13.6 20.6 14 20 14ZM21 19V17C21 16.4 20.6 16 20 16H18V20H20C20.6 20 21 19.6 21 19ZM21 7V5C21 4.4 20.6 4 20 4H18V8H20C20.6 8 21 7.6 21 7Z" fill="currentColor"/>
                                <path opacity="0.3" d="M17 22H3C2.4 22 2 21.6 2 21V3C2 2.4 2.4 2 3 2H17C17.6 2 18 2.4 18 3V21C18 21.6 17.6 22 17 22ZM10 7C8.9 7 8 7.9 8 9C8 10.1 8.9 11 10 11C11.1 11 12 10.1 12 9C12 7.9 11.1 7 10 7ZM13.3 16C14 16 14.5 15.3 14.3 14.7C13.7 13.2 12 12 10.1 12C8.10001 12 6.49999 13.1 5.89999 14.7C5.59999 15.3 6.19999 16 7.39999 16H13.3Z" fill="currentColor"/>
                                </svg></span>
                                <p class="fs-1 pt-2 text-white">Supplier</p>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col px-4 py-8 rounded-2 me-7 btn btn-hover-rise mb-7" style="background-color: #E95044;">
                    <a href="{{route('app.account.index')}}" class="text-warning fw-bold fs-6">
                        <div class="row g-0">
                            <div class="col px-6 py-8 text-center">
                                <span class="svg-icon svg-icon-light svg-icon-4hx"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                <path opacity="0.3" d="M22 12C22 17.5 17.5 22 12 22C6.5 22 2 17.5 2 12C2 6.5 6.5 2 12 2C17.5 2 22 6.5 22 12ZM12 7C10.3 7 9 8.3 9 10C9 11.7 10.3 13 12 13C13.7 13 15 11.7 15 10C15 8.3 13.7 7 12 7Z" fill="currentColor"/>
                                <path d="M12 22C14.6 22 17 21 18.7 19.4C17.9 16.9 15.2 15 12 15C8.8 15 6.09999 16.9 5.29999 19.4C6.99999 21 9.4 22 12 22Z" fill="currentColor"/>
                                </svg></span>
                                <p class="fs-1 pt-2 text-white">Akun</p>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="card-p mt-n8 position-relative">
            <!--begin::Row-->
            <div class="row g-0">
                <!--begin::Col-->
                <div class="col px-4 py-8 rounded-2 me-7 btn btn-hover-rise mb-7" style="background-color: #0F5F81;">
                    <a href="{{route('app.product.index')}}" class="text-warning fw-bold fs-6">
                        <div class="row g-0">
                            <div class="col px-6 py-8 text-center">
                                <span class="svg-icon svg-icon-light svg-icon-4hx"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                <path opacity="0.3" d="M3 13H10C10.6 13 11 13.4 11 14V21C11 21.6 10.6 22 10 22H3C2.4 22 2 21.6 2 21V14C2 13.4 2.4 13 3 13Z" fill="currentColor"/>
                                <path d="M7 16H6C5.4 16 5 15.6 5 15V13H8V15C8 15.6 7.6 16 7 16Z" fill="currentColor"/>
                                <path opacity="0.3" d="M14 13H21C21.6 13 22 13.4 22 14V21C22 21.6 21.6 22 21 22H14C13.4 22 13 21.6 13 21V14C13 13.4 13.4 13 14 13Z" fill="currentColor"/>
                                <path d="M18 16H17C16.4 16 16 15.6 16 15V13H19V15C19 15.6 18.6 16 18 16Z" fill="currentColor"/>
                                <path opacity="0.3" d="M3 2H10C10.6 2 11 2.4 11 3V10C11 10.6 10.6 11 10 11H3C2.4 11 2 10.6 2 10V3C2 2.4 2.4 2 3 2Z" fill="currentColor"/>
                                <path d="M7 5H6C5.4 5 5 4.6 5 4V2H8V4C8 4.6 7.6 5 7 5Z" fill="currentColor"/>
                                <path opacity="0.3" d="M14 2H21C21.6 2 22 2.4 22 3V10C22 10.6 21.6 11 21 11H14C13.4 11 13 10.6 13 10V3C13 2.4 13.4 2 14 2Z" fill="currentColor"/>
                                <path d="M18 5H17C16.4 5 16 4.6 16 4V2H19V4C19 4.6 18.6 5 18 5Z" fill="currentColor"/>
                                </svg></span>
                                <p class="fs-1 pt-2 text-white">Produk</p>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col px-4 py-8 rounded-2 me-7 btn btn-hover-rise mb-7" style="background-color: #F5AA3B;">
                    <a href="{{route('app.product-unit.index')}}" class="text-warning fw-bold fs-6">
                        <div class="row g-0">
                            <div class="col px-6 py-8 text-center">
                                <span class="svg-icon svg-icon-light svg-icon-4hx"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                <path opacity="0.3" d="M18 21.6C16.3 21.6 15 20.3 15 18.6V2.50001C15 2.20001 14.6 1.99996 14.3 2.19996L13 3.59999L11.7 2.3C11.3 1.9 10.7 1.9 10.3 2.3L9 3.59999L7.70001 2.3C7.30001 1.9 6.69999 1.9 6.29999 2.3L5 3.59999L3.70001 2.3C3.50001 2.1 3 2.20001 3 3.50001V18.6C3 20.3 4.3 21.6 6 21.6H18Z" fill="currentColor"/>
                                <path d="M12 12.6H11C10.4 12.6 10 12.2 10 11.6C10 11 10.4 10.6 11 10.6H12C12.6 10.6 13 11 13 11.6C13 12.2 12.6 12.6 12 12.6ZM9 11.6C9 11 8.6 10.6 8 10.6H6C5.4 10.6 5 11 5 11.6C5 12.2 5.4 12.6 6 12.6H8C8.6 12.6 9 12.2 9 11.6ZM9 7.59998C9 6.99998 8.6 6.59998 8 6.59998H6C5.4 6.59998 5 6.99998 5 7.59998C5 8.19998 5.4 8.59998 6 8.59998H8C8.6 8.59998 9 8.19998 9 7.59998ZM13 7.59998C13 6.99998 12.6 6.59998 12 6.59998H11C10.4 6.59998 10 6.99998 10 7.59998C10 8.19998 10.4 8.59998 11 8.59998H12C12.6 8.59998 13 8.19998 13 7.59998ZM13 15.6C13 15 12.6 14.6 12 14.6H10C9.4 14.6 9 15 9 15.6C9 16.2 9.4 16.6 10 16.6H12C12.6 16.6 13 16.2 13 15.6Z" fill="currentColor"/>
                                <path d="M15 18.6C15 20.3 16.3 21.6 18 21.6C19.7 21.6 21 20.3 21 18.6V12.5C21 12.2 20.6 12 20.3 12.2L19 13.6L17.7 12.3C17.3 11.9 16.7 11.9 16.3 12.3L15 13.6V18.6Z" fill="currentColor"/>
                                </svg></span>
                                <p class="fs-1 pt-2 text-white">Satuan</p>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>