routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\MainController;
use App\Http\Controllers\HRM\UserController;
use App\Http\Controllers\RegionalController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\CRM\ClientController;
use App\Http\Controllers\CRM\SupplierController;
use App\Http\Controllers\Master\ProductController;
use App\Http\Controllers\Finance\AccountController;
use App\Http\Controllers\Finance\CashFlowController;
use App\Http\Controllers\Transaction\SaleController;
use App\Http\Controllers\Master\ProductUnitController;
use App\Http\Controllers\Finance\AccountTypeController;
use App\Http\Controllers\Transaction\ExpenseController;
use App\Http\Controllers\Finance\BalanceSheetController;
use App\Http\Controllers\Transaction\PurchaseController;
use App\Http\Controllers\Master\ProductCategoryController;
use App\Http\Controllers\Transaction\SaleDetailController;
use App\Http\Controllers\Finance\IncomeStatementController;
use App\Http\Controllers\Master\ProductVariationController;
use App\Http\Controllers\Transaction\SalePaymentController;
use App\Http\Controllers\Transaction\ExpensePaymentController;
use App\Http\Controllers\Transaction\PurchaseDetailController;
use App\Http\Controllers\Transaction\ExpenseCategoryController;
use App\Http\Controllers\Transaction\PurchasePaymentController;

Route::name('app.')->group(function(){
    Route::prefix('auth')->name('auth.')->group(function(){
        Route::get('',[AuthController::class, 'index'])->name('index');
        Route::post('login',[AuthController::class, 'do_login'])->name('login');
    });
    
    Route::middleware(['auth:web'])->group(function(){
        Route::redirect('/', 'dashboard', 301);
        Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
        Route::get('report', [DashboardController::class, 'report'])->name('report');
        Route::get('keuangan', [DashboardController::class, 'keuangan'])->name('keuangan');
        Route::get('data-data', [MainController::class, 'data'])->name('data');
        Route::resource('product-category', ProductCategoryController::class);
        Route::resource('product-unit', ProductUnitController::class);
        Route::resource('product', ProductController::class);
        Route::post('product/get', [ProductController::class, 'get'])->name('product.get');
        Route::post('product/get_list', [ProductController::class, 'get_list'])->name('product.get_list');
        Route::get('product/{product}/timbang', [ProductController::class, 'timbang'])->name('product.timbang');
        Route::post('product/timbang/store', [ProductController::class, 'timbang_store'])->name('product.timbang.store');
        Route::resource('product-variation', ProductVariationController::class);
        Route::post('product-variation/get_list', [ProductVariationController::class, 'get_list'])->name('product-variation.get_list');
        Route::resource('supplier', SupplierController::class);
        Route::post('supplier/get', [SupplierController::class, 'get'])->name('supplier.get');
        Route::post('supplier/get_list', [SupplierController::class, 'get_list'])->name('supplier.get_list');
        Route::resource('client', ClientController::class);
        Route::post('client/get', [ClientController::class, 'get'])->name('client.get');
        Route::post('client/get_list', [ClientController::class, 'get_list'])->name('client.get_list');
        Route::resource('user', UserController::class);
        Route::resource('account-type', AccountTypeController::class);
        Route::resource('account', AccountController::class);
        Route::resource('purchase', PurchaseController::class);
        Route::resource('purchase-detail', PurchaseDetailController::class);
        Route::resource('purchase-payment', PurchasePaymentController::class);
        Route::post('purchase/{purchase}/process', [PurchaseController::class, 'process'])->name('purchase.process');
        Route::post('purchase/{purchase}/finish', [PurchaseController::class, 'finish'])->name('purchase.finish');
        Route::resource('sale', SaleController::class);
        Route::resource('sale-detail', SaleDetailController::class);
        Route::resource('sale-payment', SalePaymentController::class);
        Route::get('cash-flow', [CashFlowController::class, 'index'])->name('cash-flow.index');
        Route::get('income-statement', [IncomeStatementController::class, 'index'])->name('income-statement.index');
        Route::get('balance-sheet', [BalanceSheetController::class, 'index'])->name('balance-sheet.index');
        Route::post('sale/{sale}/process', [SaleController::class, 'process'])->name('sale.process');
        Route::post('sale/{sale}/finish', [SaleController::class, 'finish'])->name('sale.finish');
        Route::resource('expense-category', ExpenseCategoryController::class);
        Route::get('expense/{expense}/journal', [ExpenseController::class, 'journal'])->name('expense.journal');
        Route::resource('expense', ExpenseController::class);
        Route::resource('expense-payment', ExpensePaymentController::class);
        Route::post('city/get_city', [RegionalController::class, 'get_city'])->name('regional.get_city');
        Route::post('subdistrict/get_subdistrict', [RegionalController::class, 'get_subdistrict'])->name('regional.get_subdistrict');
        Route::get('logout',[AuthController::class, 'do_logout'])->name('auth.logout');
    });
});

app/Models/Expense.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Expense extends Model
{
    use HasFactory;
    protected $casts = [
        'date' => 'date',
    ];
    public function category()
    {
        return $this->belongsTo(Account::class,'expense_category_id','id');
    }
    public function payments()
    {
        return $this->hasMany(ExpensePayment::class,'expense_id','id');
    }
}

app/Http/Controllers/Transaction/ExpenseController.php
<?php

namespace App\Http\Controllers\Transaction;

use App\Helpers\Helper;
use App\Models\Account;
use App\Models\Expense;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Models\ExpenseCategory;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;

class ExpenseController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $keywords = $request->keyword;
            $collection = Expense::where('code','LIKE','%'.$keywords.'%')->orderBy('id', 'ASC')->paginate(10);
            return view('page.expense.list', compact('collection'));
        }
        return view('page.expense.main');
    }
    public function create()
    {
        $category = Account::where('account_type_id',5)->get();
        return view('page.expense.input', ['data' => new Expense, 'category' => $category]);
    }
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'jenis_pengeluaran' => 'required',
            'tanggal' => 'required',
            'total_pengeluaran' => 'required',
            'dokumen' => 'mimes:pdf',
        ]);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('jenis_pengeluaran')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('jenis_pengeluaran'),
                ]);
            }
            elseif ($errors->has('tanggal')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('tanggal'),
                ]);
            }
            elseif ($errors->has('total_pengeluaran')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('total_pengeluaran'),
                ]);
            }
            elseif ($errors->has('dokumen')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('dokumen'),
                ]);
            }
        }
        if ($request->code){
            $code = $request->code.'-';
        }else{
            $code = 'EXP-';
        }
        $generator = Helper::code_generator(new Expense,$code);
        $data = new Expense;
        $data->code = $generator;
        $data->date = $request->tanggal;
        $data->expense_category_id = $request->jenis_pengeluaran;
        $data->grand_total = Str::remove(',',$request->total_pengeluaran);
        if(request()->file('dokumen')){
            $dokumen = request()->file('dokumen')->store("dokumen_pengeluaran");
            $data->document = $dokumen;
        }
        $data->save();
        return response()->json([
            'alert' => 'success',
            'message' => 'Pengeluaran tersimpan',
            'redirect' => 'input',
            'route' => route('app.expense.edit',$data->id),
        ]);
    }
    public function show(Expense $expense)
    {
        //
    }
    public function edit(Expense $expense)
    {
        $akun = Account::get();
        $category = Account::where('account_type_id',5)->get();
        return view('page.expense.input', ['data' => $expense, 'akun' => $akun, 'category' => $category]);
    }
    public function update(Request $request, Expense $expense)
    {
        $validator = Validator::make($request->all(), [
            'jenis_pengeluaran' => 'required',
            'tanggal' => 'required',
            'total_pengeluaran' => 'required',
            'dokumen' => 'mimes:pdf',
        ]);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('jenis_pengeluaran')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('jenis_pengeluaran'),
                ]);
            }
            elseif ($errors->has('tanggal')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('tanggal'),
                ]);
            }
            elseif ($errors->has('total_pengeluaran')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('total_pengeluaran'),
                ]);
            }
            elseif ($errors->has('dokumen')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('dokumen'),
                ]);
            }
        }
        $expense->expense_category_id = $request->jenis_pengeluaran;
        $expense->grand_total = Str::remove(',',$request->total_pengeluaran);
        if(request()->file('dokumen')){
            Storage::delete($expense->document);
            $dokumen = request()->file('dokumen')->store("dokumen_pengeluaran");
            $expense->document = $dokumen;
        }
        $expense->update();
        return response()->json([
            'alert' => 'success',
            'message' => 'Pengeluaran terubah',
            'redirect' => 'input',
            'route' => route('app.expense.edit',$expense->id),
        ]);
    }
    public function destroy(Expense $expense)
    {
        Storage::delete($expense->document);
        $expense->delete();
        return response()->json([
            'alert' => 'success',
            'message' => 'Pengeluaran terhapus',
        ]);
    }
    public function journal(Expense $expense)
    {
        $akun = Account::get();
        $category = ExpenseCategory::get();
        return view('page.expense.journal', ['data' => $expense, 'akun' => $akun, 'category' => $category]);
    }
}

resources/views/page/expense/input.blade.php
<div id="kt_content_container" class="container-xxl">
    <div class="card">
        <div class="card-body pb-5">
            <form id="form_input">
                <div class="row">
                    <div class="col-lg-6">
                        <label class="required fs-6 fw-bold mb-2">Kode</label>
                        <input type="text" class="form-control" name="kode" placeholder="Masukkan Kode..." value="{{$data->code}}" {{$data->code ? 'readonly': ''}}>
                    </div>
                    <div class="col-lg-6">
                        <label class="fs-6 fw-bold mb-2">Jenis Pengeluaran</label>
                        <select class="form-control" name="jenis_pengeluaran" id="jenis_pengeluaran">
                            <option value="" selected disabled>Pilih Jenis Pengeluaran</option>
                            @foreach ($category as $item)
                            <option value="{{$item->id}}" {{$data->expense_category_id == $item->id ? 'selected' : ''}}>{{$item->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="col-lg-4">
                        <label class="required fs-6 fw-bold mb-2">Tanggal</label>
                        <input type="text" class="form-control" id="tanggal" name="tanggal" placeholder="Masukkan tanggal..." value="{{$data->date}}">
                    </div>
                    <div class="col-lg-4">
                        <label class="required fs-6 fw-bold mb-2">Total Pengeluaran</label>
                        <input type="text" class="form-control" id="total_pengeluaran" name="total_pengeluaran" placeholder="Masukkan Total Pengeluaran..." value="{{number_format($data->grand_total)}}">
                    </div>
                    <div class="col-lg-4">
                        <label class="fs-6 fw-bold mb-2">Dokumen Pendukung</label>
                        <input type="file" class="form-control" accept="application/pdf" id="dokumen" name="dokumen" placeholder="Masukkan Dokumen Pendukung...">
                    </div>
                    <div class="min-w-150px mt-10 text-end">
                        <a href="javascript:;" onclick="load_list(1);" class="btn btn-sm btn-primary">Kembali</a>
                        @if ($data->id)
                        <button id="tombol_simpan" onclick="handle_upload('#tombol_simpan','#form_input','{{route('app.expense.update',$data->id)}}','PATCH');" class="btn btn-sm btn-warning text-black">Simpan</button>
                        @else
                        <button id="tombol_simpan" onclick="handle_upload('#tombol_simpan','#form_input','{{route('app.expense.store')}}','POST');" class="btn btn-sm btn-success">Simpan</button>
                        @endif
                    </div>
                </div>
            </form>
        </div>
    </div>
    @if($data->id)
    <div class="card">
        <div class="card-body pb-5">
            <form id="form_input_payment">
                <div class="row">
                    <div class="col-lg-5">
                        <input type="hidden" class="form-control" name="id" value="{{$data->id}}">
                        <label class="required fs-6 fw-bold mb-2">Akun</label>
                        <select class="form-control" name="akun">
                            <option value="" SELECTED DISABLED>Pilih Akun</option>
                            @foreach ( $akun as $item)
                            <option value="{{$item->id}}">{{$item->code}} - {{$item->name}} | Rp {{number_format($item->balance)}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="col-lg-3">
                        <label class="required fs-6 fw-bold mb-2">Tanggal</label>
                        <input type="text" class="form-control" id="tanggal_bayar" name="tanggal_bayar">
                    </div>
                    <div class="col-lg-4">
                        <label class="required fs-6 fw-bold mb-2">Jumlah Bayar</label>
                        <input type="tel" class="form-control" id="jumlah_bayar" name="jumlah_bayar">
                    </div>
                    @if ($data->payment_st == "Belum lunas")
                    <div class="col-lg-4 mt-5">
                        <button id="tombol_simpan_payment" onclick="handle_save('#tombol_simpan_payment','#form_input_payment','{{route('app.expense-payment.store')}}','POST');" class="btn btn-sm btn-success mt-8">Tambah Pembayaran</button>
                    </div>
                    @endif
                </div>
            </form>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table align-middle table-row-dashed fs-6 gy-5">
                    <thead>
                        <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
                            <th class="min-w-125px">Tanggal Bayar</th>
                            <th class="min-w-125px">Akun</th>
                            <th class="min-w-125px">Jumlah Bayar</th>
                            <th class="text-end min-w-70px">Aksi</th>
                        </tr>
                    </thead>
                    <tbody class="fw-bold text-gray-600">
                        @php
                        $total_bayar = 0;
                        @endphp
                        @foreach ($data->payments as $item)
                        @php
                        $total_bayar += $item->total;
                        @endphp
                        <tr>
                            <td>
                                <a href="javascript:;" class="text-gray-800 text-hover-primary mb-1">{{$item->date->format('j F Y')}}</a>
                            </td>
                            <td>
                                <a href="javascript:;" class="text-gray-800 text-hover-primary mb-1">{{$item->account->name}}</a>
                            </td>
                            <td>
                                <a href="javascript:;" class="text-gray-800 text-hover-primary mb-1">{{number_format($item->total)}}</a>
                            </td>
                            <td class="text-end">
                                @if ($data->st != "Tertunda")
                                <div class="btn-group" role="group">
                                    <button id="aksi" type="button" class="btn btn-sm btn-light btn-active-light-primary" data-bs-toggle="dropdown" aria-expanded="false">
                                        Aksi
                                        <span class="svg-icon svg-icon-5 m-0">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                                <path d="M11.4343 12.7344L7.25 8.55005C6.83579 8.13583 6.16421 8.13584 5.75 8.55005C5.33579 8.96426 5.33579 9.63583 5.75 10.05L11.2929 15.5929C11.6834 15.9835 12.3166 15.9835 12.7071 15.5929L18.25 10.05C18.6642 9.63584 18.6642 8.96426 18.25 8.55005C17.8358 8.13584 17.1642 8.13584 16.75 8.55005L12.5657 12.7344C12.2533 13.0468 11.7467 13.0468 11.4343 12.7344Z" fill="black" />
                                            </svg>
                                        </span>
                                    </button>
                                    <div class="dropdown-menu menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-bold fs-7 w-125px py-4" aria-labelledby="aksi">
                                        <div class="menu-item px-3">
                                            <a href="javascript:;" onclick="handle_confirm('Apakah Anda Yakin?','Yakin','Tidak','DELETE','{{route('app.expense-payment.destroy',$item->id)}}');" class="menu-link px-3">Hapus</a>
                                        </div>
                                    </div>
                                </div>
                                @endif
                            </td>
                        </tr>
                        @endforeach
                        <tr>
                            <td colspan="2">Total</td>
                            <td>{{number_format($total_bayar)}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    @endif
</div>
<script>
    obj_enddatenow('tanggal');
    number_only('total_pengeluaran');
    ribuan('total_pengeluaran');
    obj_select('jenis_pengeluaran', 'Pilih Jenis Pengeluaran');
    obj_enddatenow('tanggal_bayar');
    number_only('jumlah_bayar');
    ribuan('jumlah_bayar');
</script>

resources/views/page/expense/journal.blade.php
<div id="kt_content_container" class="container-xxl">
    <div class="card">
        <div class="card-body pb-5">
            <form id="form_input">
                <div class="row">
                    <div class="col-lg-4">
                        <label class="fs-6 fw-bold mb-2">Jenis</label>
                        <select class="form-control" name="jenis_pengeluaran" id="jenis_pengeluaran">
                            <option value="" selected disabled>Pilih Jenis</option>
                            <option value="D" {{$data->expense_category_id == "D" ? 'selected' : ''}}>Debit</option>
                            <option value="K" {{$data->expense_category_id == "K" ? 'selected' : ''}}>Kredit</option>
                        </select>
                    </div>
                    <div class="col-lg-4">
                        <label class="required fs-6 fw-bold mb-2">Tanggal</label>
                        <input type="text" class="form-control" id="tanggal" name="tanggal" placeholder="Masukkan tanggal..." value="{{$data->date}}">
                    </div>
                    <div class="col-lg-4">
                        <label class="required fs-6 fw-bold mb-2">Jumlah</label>
                        <input type="text" class="form-control" id="total_pengeluaran" name="total_pengeluaran" placeholder="Masukkan Total Pengeluaran..." value="{{number_format($data->grand_total)}}">
                    </div>
                    <div class="min-w-150px mt-10 text-end">
                        <a href="javascript:;" onclick="load_list(1);" class="btn btn-sm btn-primary">Kembali</a>
                        @if ($data->id)
                        <button id="tombol_simpan" onclick="handle_upload('#tombol_simpan','#form_input','{{route('app.expense.update',$data->id)}}','PATCH');" class="btn btn-sm btn-warning text-black">Simpan</button>
                        @else
                        <button id="tombol_simpan" onclick="handle_upload('#tombol_simpan','#form_input','{{route('app.expense.store')}}','POST');" class="btn btn-sm btn-success">Simpan</button>
                        @endif
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    obj_enddatenow('tanggal');
    number_only('total_pengeluaran');
    ribuan('total_pengeluaran');
    obj_select('jenis_pengeluaran', 'Pilih Jenis Pengeluaran');
    obj_enddatenow('tanggal_bayar');
    number_only('jumlah_bayar');
    ribuan('jumlah_bayar');
</script>

resources/views/page/expense/list.blade.php
<table class="table align-middle table-row-dashed fs-6 gy-5">
    <thead>
        <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
            <th class="min-w-125px">Kode</th>
            <th class="min-w-125px">Tanggal</th>
            <th class="min-w-125px">Jenis Pengeluaran</th>
            <th class="min-w-125px">Grand Total</th>
            <th class="min-w-125px">Total Pembayaran</th>
            <th class="min-w-125px">Status Pembayaran</th>
            <th class="text-end min-w-70px">Aksi</th>
        </tr>
    </thead>
    <tbody class="fw-bold text-gray-600">
        @if ($collection->count() > 0)
            @foreach ($collection as $item)
            <tr>
                <td>
                    <a href="javascript:;" class="text-gray-800 text-hover-primary mb-1">{{$item->code}}</a>
                </td>
                <td>
                    <a href="javascript:;" class="text-gray-800 text-hover-primary mb-1">{{$item->date->format('j F Y')}}</a>
                </td>
                <td>
                    <a href="javascript:;" class="text-gray-800 text-hover-primary mb-1">{{$item->category->name}}</a>
                </td>
                <td>
                    <a href="javascript:;" class="text-gray-800 text-hover-primary mb-1">{{number_format($item->grand_total)}}</a>
                </td>
                <td>
                    <a href="javascript:;" class="text-gray-800 text-hover-primary mb-1">{{number_format($item->total_payment)}}</a>
                </td>
                <td>
                    <a href="javascript:;" class="text-gray-800 text-hover-primary mb-1">{{$item->payment_st}}</a>
                </td>
                <td class="text-end">
                    <div class="btn-group" role="group">
                        <button id="aksi" type="button" class="btn btn-sm btn-light btn-active-light-primary" data-bs-toggle="dropdown" aria-expanded="false">Aksi
                            <span class="svg-icon svg-icon-5 m-0">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                    <path d="M11.4343 12.7344L7.25 8.55005C6.83579 8.13583 6.16421 8.13584 5.75 8.55005C5.33579 8.96426 5.33579 9.63583 5.75 10.05L11.2929 15.5929C11.6834 15.9835 12.3166 15.9835 12.7071 15.5929L18.25 10.05C18.6642 9.63584 18.6642 8.96426 18.25 8.55005C17.8358 8.13584 17.1642 8.13584 16.75 8.55005L12.5657 12.7344C12.2533 13.0468 11.7467 13.0468 11.4343 12.7344Z" fill="black" />
                                </svg>
                            </span>
                        </button>
                        <div class="dropdown-menu menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-bold fs-7 w-125px py-4" aria-labelledby="aksi">
                            <div class="menu-item px-3">
                                <a href="javascript:;" onclick="load_input('{{route('app.expense.edit',$item->id)}}');" class="menu-link px-3">Perbarui</a>
                            </div>
                            <div class="menu-item px-3">
                                <a href="javascript:;" onclick="handle_confirm('Apakah Anda Yakin?','Yakin','Tidak','DELETE','{{route('app.expense.destroy',$item->id)}}');" class="menu-link px-3">Hapus</a>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
            @endforeach
        @else
        <tr>
            <td colspan="7" class="text-center">
                <a href="javascript:;" class="text-gray-800 text-hover-primary mb-1">Tidak ada data</a>
            </td>
        </tr>
        @endif
    </tbody>
</table>
{{$collection->links('theme.app.pagination')}}