routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\MainController;
use App\Http\Controllers\HRM\UserController;
use App\Http\Controllers\RegionalController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\CRM\ClientController;
use App\Http\Controllers\CRM\SupplierController;
use App\Http\Controllers\Master\ProductController;
use App\Http\Controllers\Finance\AccountController;
use App\Http\Controllers\Finance\CashFlowController;
use App\Http\Controllers\Transaction\SaleController;
use App\Http\Controllers\Master\ProductUnitController;
use App\Http\Controllers\Finance\AccountTypeController;
use App\Http\Controllers\Transaction\ExpenseController;
use App\Http\Controllers\Finance\BalanceSheetController;
use App\Http\Controllers\Transaction\PurchaseController;
use App\Http\Controllers\Master\ProductCategoryController;
use App\Http\Controllers\Transaction\SaleDetailController;
use App\Http\Controllers\Finance\IncomeStatementController;
use App\Http\Controllers\Master\ProductVariationController;
use App\Http\Controllers\Transaction\SalePaymentController;
use App\Http\Controllers\Transaction\ExpensePaymentController;
use App\Http\Controllers\Transaction\PurchaseDetailController;
use App\Http\Controllers\Transaction\ExpenseCategoryController;
use App\Http\Controllers\Transaction\PurchasePaymentController;

Route::name('app.')->group(function(){
    Route::prefix('auth')->name('auth.')->group(function(){
        Route::get('',[AuthController::class, 'index'])->name('index');
        Route::post('login',[AuthController::class, 'do_login'])->name('login');
    });
    
    Route::middleware(['auth:web'])->group(function(){
        Route::redirect('/', 'dashboard', 301);
        Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
        Route::get('report', [DashboardController::class, 'report'])->name('report');
        Route::get('keuangan', [DashboardController::class, 'keuangan'])->name('keuangan');
        Route::get('data-data', [MainController::class, 'data'])->name('data');
        Route::resource('product-category', ProductCategoryController::class);
        Route::resource('product-unit', ProductUnitController::class);
        Route::resource('product', ProductController::class);
        Route::post('product/get', [ProductController::class, 'get'])->name('product.get');
        Route::post('product/get_list', [ProductController::class, 'get_list'])->name('product.get_list');
        Route::get('product/{product}/timbang', [ProductController::class, 'timbang'])->name('product.timbang');
        Route::post('product/timbang/store', [ProductController::class, 'timbang_store'])->name('product.timbang.store');
        Route::resource('product-variation', ProductVariationController::class);
        Route::post('product-variation/get_list', [ProductVariationController::class, 'get_list'])->name('product-variation.get_list');
        Route::resource('supplier', SupplierController::class);
        Route::post('supplier/get', [SupplierController::class, 'get'])->name('supplier.get');
        Route::post('supplier/get_list', [SupplierController::class, 'get_list'])->name('supplier.get_list');
        Route::resource('client', ClientController::class);
        Route::post('client/get', [ClientController::class, 'get'])->name('client.get');
        Route::post('client/get_list', [ClientController::class, 'get_list'])->name('client.get_list');
        Route::resource('user', UserController::class);
        Route::resource('account-type', AccountTypeController::class);
        Route::resource('account', AccountController::class);
        Route::resource('purchase', PurchaseController::class);
        Route::resource('purchase-detail', PurchaseDetailController::class);
        Route::resource('purchase-payment', PurchasePaymentController::class);
        Route::post('purchase/{purchase}/process', [PurchaseController::class, 'process'])->name('purchase.process');
        Route::post('purchase/{purchase}/finish', [PurchaseController::class, 'finish'])->name('purchase.finish');
        Route::resource('sale', SaleController::class);
        Route::resource('sale-detail', SaleDetailController::class);
        Route::resource('sale-payment', SalePaymentController::class);
        Route::get('cash-flow', [CashFlowController::class, 'index'])->name('cash-flow.index');
        Route::get('income-statement', [IncomeStatementController::class, 'index'])->name('income-statement.index');
        Route::get('balance-sheet', [BalanceSheetController::class, 'index'])->name('balance-sheet.index');
        Route::post('sale/{sale}/process', [SaleController::class, 'process'])->name('sale.process');
        Route::post('sale/{sale}/finish', [SaleController::class, 'finish'])->name('sale.finish');
        Route::resource('expense-category', ExpenseCategoryController::class);
        Route::get('expense/{expense}/journal', [ExpenseController::class, 'journal'])->name('expense.journal');
        Route::resource('expense', ExpenseController::class);
        Route::resource('expense-payment', ExpensePaymentController::class);
        Route::post('city/get_city', [RegionalController::class, 'get_city'])->name('regional.get_city');
        Route::post('subdistrict/get_subdistrict', [RegionalController::class, 'get_subdistrict'])->name('regional.get_subdistrict');
        Route::get('logout',[AuthController::class, 'do_logout'])->name('auth.logout');
    });
});

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    use HasFactory;
    public function province()
    {
        return $this->belongsTo(Province::class,'province_id','id');
    }
    public function city()
    {
        return $this->belongsTo(City::class,'city_id','id');
    }
    public function subdistrict()
    {
        return $this->belongsTo(Subdistrict::class,'subdistrict_id','id');
    }
}

app/Http/Controllers/CRM/ClientController.php
<?php

namespace App\Http\Controllers\CRM;

use App\Models\Client;
use App\Helpers\Helper;
use App\Models\Province;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class ClientController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $keywords = $request->keyword;
            $collection = Client::where('name','LIKE','%'.$keywords.'%')->orderBy('id', 'ASC')->paginate(10);
            return view('page.client.list', compact('collection'));
        }
        return view('page.client.main');
    }
    public function create()
    {
        $propinsi = Province::get();
        return view('page.client.input', ['data' => new Client, 'propinsi' => $propinsi]);
    }
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            // 'propinsi' => 'required',
            // 'kota' => 'required',
            // 'kecamatan' => 'required',
            // 'alamat' => 'required',
            // 'telp' => 'required',
        ]);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('name')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('name'),
                ]);
            }
            // elseif ($errors->has('propinsi')) {
            //     return response()->json([
            //         'alert' => 'error',
            //         'message' => $errors->first('propinsi'),
            //     ]);
            // }
            // elseif ($errors->has('kota')) {
            //     return response()->json([
            //         'alert' => 'error',
            //         'message' => $errors->first('kota'),
            //     ]);
            // }
            // elseif ($errors->has('kecamatan')) {
            //     return response()->json([
            //         'alert' => 'error',
            //         'message' => $errors->first('kecamatan'),
            //     ]);
            // }
            // elseif ($errors->has('alamat')) {
            //     return response()->json([
            //         'alert' => 'error',
            //         'message' => $errors->first('alamat'),
            //     ]);
            // }
            // elseif ($errors->has('telp')) {
            //     return response()->json([
            //         'alert' => 'error',
            //         'message' => $errors->first('telp'),
            //     ]);
            // }
        }
        if ($request->kode){
            $code = $request->kode.'-';
        }else{
            $code = 'CUST-';
        }
        $generator = Helper::code_generator(new Client,$code);
        $data = new Client;
        $data->code = $generator;
        $data->name = $request->name;
        $data->province_id = $request->propinsi;
        $data->city_id = $request->kota;
        $data->subdistrict_id = $request->kecamatan;
        $data->address = $request->alamat;
        $data->telp_1 = $request->telp_1;
        $data->telp_2 = $request->telp_2;
        $data->phone = $request->phone;
        $data->save();
        return response()->json([
            'alert' => 'success',
            'message' => 'Pelanggan tersimpan',
        ]);
    }
    public function show(Client $client)
    {
        //
    }
    public function edit(Client $client)
    {
        $propinsi = Province::get();
        return view('page.client.input', ['data' => $client, 'propinsi' => $propinsi]);
    }
    public function update(Request $request, Client $client)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            // 'propinsi' => 'required',
            // 'kota' => 'required',
            // 'kecamatan' => 'required',
            // 'alamat' => 'required',
            // 'telp' => 'required',
        ]);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('name')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('name'),
                ]);
            }
            // elseif ($errors->has('propinsi')) {
            //     return response()->json([
            //         'alert' => 'error',
            //         'message' => $errors->first('propinsi'),
            //     ]);
            // }
            // elseif ($errors->has('kota')) {
            //     return response()->json([
            //         'alert' => 'error',
            //         'message' => $errors->first('kota'),
            //     ]);
            // }
            // elseif ($errors->has('kecamatan')) {
            //     return response()->json([
            //         'alert' => 'error',
            //         'message' => $errors->first('kecamatan'),
            //     ]);
            // }
            // elseif ($errors->has('alamat')) {
            //     return response()->json([
            //         'alert' => 'error',
            //         'message' => $errors->first('alamat'),
            //     ]);
            // }
            // elseif ($errors->has('telp')) {
            //     return response()->json([
            //         'alert' => 'error',
            //         'message' => $errors->first('telp'),
            //     ]);
            // }
        }
        $client->name = $request->name;
        $client->province_id = $request->propinsi;
        $client->city_id = $request->kota;
        $client->subdistrict_id = $request->kecamatan;
        $client->address = $request->alamat;
        $client->telp_1 = $request->telp_1;
        $client->telp_2 = $request->telp_2;
        $client->phone = $request->phone;
        $client->update();
        return response()->json([
            'alert' => 'success',
            'message' => 'Pelanggan terubah',
        ]);
    }
    public function destroy(Client $client)
    {
        $client->delete();
        return response()->json([
            'alert' => 'success',
            'message' => 'Pelanggan terhapus',
        ]);
    }
    public function get(Request $request)
    {
        $client = Client::where('code','=',$request->code)->first();
        if(!$client){
            return response()->json([
                'alert' => 'info',
                'message' => 'Client tidak ditemukan',
            ]);
        }else{
            return response()->json([
                'alert' => 'success',
                'data' => $client,
                'message' => 'Client ditemukan',
            ]);
        }
    }
    public function get_list()
    {
        $collection = Client::get();
        return view('page.client.list_modal', ['collection' => $collection]);
    }
}

resources/views/page/client/input.blade.php
<div id="kt_content_container" class="container-xxl">
    <div class="card">
        <div class="card-body pb-5">
            <form id="form_input">
                <div class="row">
                    <div class="col-lg-6">
                        <label class="required fs-6 fw-bold mb-2">Kode</label>
                        <input type="text" class="form-control" name="kode" placeholder="Masukkan Kode..." value="{{$data->code}}" {{$data->code ? 'readonly': ''}}>
                    </div>
                    <div class="col-lg-6">
                        <label class="required fs-6 fw-bold mb-2">Nama</label>
                        <input type="text" class="form-control" name="name" placeholder="Masukkan nama..." value="{{$data->name}}">
                    </div>
                    <div class="col-lg-4 mt-5">
                        <label class="required fs-6 fw-bold mb-2">Propinsi</label>
                        <select class="form-control" name="propinsi" id="propinsi">
                            <option value="" selected disabled>Pilih Propinsi</option>
                            @foreach ($propinsi as $item)
                                <option value="{{$item->id}}" {{$data->province_id == $item->id ? 'selected' : ''}}>{{$item->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="col-lg-4 mt-5">
                        <label class="required fs-6 fw-bold mb-2">Kota</label>
                        <select class="form-control" name="kota" id="kota">
                            <option value="" selected disabled>Pilih Propinsi terlebih dahulu</option>
                        </select>
                    </div>
                    <div class="col-lg-4 mt-5">
                        <label class="required fs-6 fw-bold mb-2">Kecamatan</label>
                        <select class="form-control" name="kecamatan" id="kecamatan">
                            <option value="" selected disabled>Pilih Kota terlebih dahulu</option>
                        </select>
                    </div>
                    <div class="col-lg-12 mt-5">
                        <label class="required fs-6 fw-bold mb-2">Alamat</label>
                        <textarea class="form-control" name="alamat" id="alamat">{{$data->address}}</textarea>
                    </div>
                    <div class="col-lg-4 mt-5">
                        <label class="required fs-6 fw-bold mb-2">No Telp 1</label>
                        <input type="tel" maxlength="13" class="form-control" id="telp_1" name="telp_1" value="{{$data->telp_1}}">
                    </div>
                    <div class="col-lg-4 mt-5">
                        <label class="required fs-6 fw-bold mb-2">No Telp 2</label>
                        <input type="tel" maxlength="13" class="form-control" id="telp_2" name="telp_2" value="{{$data->telp_2}}">
                    </div>
                    <div class="col-lg-4 mt-5">
                        <label class="required fs-6 fw-bold mb-2">No HP</label>
                        <input type="tel" maxlength="13" class="form-control" id="phone" name="phone" value="{{$data->phone}}">
                    </div>
                    <div class="min-w-150px mt-10 text-end">
                        <a href="javascript:;" onclick="load_list(1);" class="btn btn-sm btn-primary">Kembali</a>
                        @if ($data->id)
                        <button id="tombol_simpan" onclick="handle_save('#tombol_simpan','#form_input','{{route('app.client.update',$data->id)}}','PATCH');" class="btn btn-sm btn-warning text-black">Simpan</button>
                        @else
                        <button id="tombol_simpan" onclick="handle_save('#tombol_simpan','#form_input','{{route('app.client.store')}}','POST');" class="btn btn-sm btn-success">Simpan</button>
                        @endif
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    obj_select('propinsi', 'Pilih Propinsi');
    obj_select('kota', 'Pilih Kota');
    obj_select('kecamatan', 'Pilih Kecamatan');
    obj_autosize('alamat');
    number_only('telp_1');
    number_only('telp_2');
    number_only('phone');
    @if($data->province_id)
    $('#propinsi').val('{{$data->province_id}}');
    setTimeout(function(){ 
        $('#propinsi').trigger('change');
        setTimeout(function(){ 
            $('#kota').val('{{$data->city_id}}');
            $('#kota').trigger('change');
            setTimeout(function(){ 
                $('#kecamatan').val('{{$data->subdistrict_id}}');
                $('#kecamatan').trigger('change');
            }, 1500);
        }, 1200);
    }, 1000);
    @endif
    $("#propinsi").change(function(){
        $.ajax({
            type: "POST",
            url: "{{route('app.regional.get_city')}}",
            data: {propinsi : $("#propinsi").val()},
            success: function(response){
                $("#kota").html(response);
            }
        });
    });
    $("#kota").change(function(){
        $.ajax({
            type: "POST",
            url: "{{route('app.regional.get_subdistrict')}}",
            data: {kota : $("#kota").val()},
            success: function(response){
                $("#kecamatan").html(response);
            }
        });
    });
</script>

resources/views/page/client/list.blade.php
<table class="table align-middle table-row-dashed fs-6 gy-5">
    <thead>
        <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
            <th class="min-w-125px">Kode</th>
            <th class="min-w-125px">Nama</th>
            <th class="min-w-125px">No Telp & No HP</th>
            <th class="min-w-125px">Alamat</th>
            <th class="text-end min-w-70px">Aksi</th>
        </tr>
    </thead>
    <tbody class="fw-bold text-gray-600">
        @if ($collection->count() > 0)
            @foreach ($collection as $item)
            <tr>
                <td>
                    <a href="javascript:;" class="text-gray-800 text-hover-primary mb-1">{{$item->code}}</a>
                </td>
                <td>
                    <a href="javascript:;" class="text-gray-800 text-hover-primary mb-1">{{$item->name}}</a>
                </td>
                <td>
                    <a href="javascript:;" class="text-gray-800 text-hover-primary mb-1">{{$item->telp_1 ?? 0}} | {{$item->telp_2 ?? 0}} | {{$item->phone ?? 0}}</a>
                </td>
                <td>
                    <a href="javascript:;" class="text-gray-800 text-hover-primary mb-1">
                        {{$item->address}} <br>
                        @if ($item->subdistrict_id)
                        {{$item->subdistrict->name}},
                        @endif
                        @if ($item->city_id)
                        {{$item->city->name}}.<br>
                        @endif
                        @if ($item->province_id)
                        {{$item->province->name}},
                        @endif
                        @if ($item->city_id)
                        {{$item->city->code}}
                        @endif
                    </a>
                </td>
                <td class="text-end">
                    <div class="btn-group" role="group">
                        <button id="aksi" type="button" class="btn btn-sm btn-light btn-active-light-primary" data-bs-toggle="dropdown" aria-expanded="false">Aksi
                            <span class="svg-icon svg-icon-5 m-0">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                    <path d="M11.4343 12.7344L7.25 8.55005C6.83579 8.13583 6.16421 8.13584 5.75 8.55005C5.33579 8.96426 5.33579 9.63583 5.75 10.05L11.2929 15.5929C11.6834 15.9835 12.3166 15.9835 12.7071 15.5929L18.25 10.05C18.6642 9.63584 18.6642 8.96426 18.25 8.55005C17.8358 8.13584 17.1642 8.13584 16.75 8.55005L12.5657 12.7344C12.2533 13.0468 11.7467 13.0468 11.4343 12.7344Z" fill="black" />
                                </svg>
                            </span>
                        </button>
                        <div class="dropdown-menu menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-bold fs-7 w-125px py-4" aria-labelledby="aksi">
                            <div class="menu-item px-3">
                                <a href="javascript:;" onclick="load_input('{{route('app.client.edit',$item->id)}}');" class="menu-link px-3">Perbarui</a>
                            </div>
                            <div class="menu-item px-3">
                                <a href="javascript:;" onclick="handle_confirm('Apakah Anda Yakin?','Yakin','Tidak','DELETE','{{route('app.client.destroy',$item->id)}}');" class="menu-link px-3">Hapus</a>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
            @endforeach
        @else
        <tr>
            <td colspan="5" class="text-center">
                <a href="javascript:;" class="text-gray-800 text-hover-primary mb-1">Tidak ada data</a>
            </td>
        </tr>
        @endif
    </tbody>
</table>
{{$collection->links('theme.app.pagination')}}

resources/views/page/client/main.blade.php
<x-app-layout title="Pelanggan">
    <div id="content_list">
        <div class="container-xxl" id="kt_content_container">
            <div class="card">
                <div class="card-header border-0 pt-6">
                    <div class="card-title">
                        <form id="content_filter">
                            <div class="d-flex align-items-center position-relative my-1">
                                <span class="svg-icon svg-icon-1 position-absolute ms-6">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                        <path d="M21.7 18.9L18.6 15.8C17.9 16.9 16.9 17.9 15.8 18.6L18.9 21.7C19.3 22.1 19.9 22.1 20.3 21.7L21.7 20.3C22.1 19.9 22.1 19.3 21.7 18.9Z" fill="black" />
                                        <path opacity="0.3" d="M11 20C6 20 2 16 2 11C2 6 6 2 11 2C16 2 20 6 20 11C20 16 16 20 11 20ZM11 4C7.1 4 4 7.1 4 11C4 14.9 7.1 18 11 18C14.9 18 18 14.9 18 11C18 7.1 14.9 4 11 4ZM8 11C8 9.3 9.3 8 11 8C11.6 8 12 7.6 12 7C12 6.4 11.6 6 11 6C8.2 6 6 8.2 6 11C6 11.6 6.4 12 7 12C7.6 12 8 11.6 8 11Z" fill="black" />
                                    </svg>
                                </span>
                                <input name="keyword" onkeyup="load_list(1);" type="text" class="form-control form-control-solid w-250px ps-15" placeholder="Pencarian data..." />
                            </div>
                        </form>
                    </div>
                    <div class="card-toolbar">
                        <div class="d-flex justify-content-end" data-kt-customer-table-toolbar="base">
                            <button type="button" class="btn btn-light-primary me-3 d-none" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">
                                <span class="svg-icon svg-icon-2">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                        <path d="M19.0759 3H4.72777C3.95892 3 3.47768 3.83148 3.86067 4.49814L8.56967 12.6949C9.17923 13.7559 9.5 14.9582 9.5 16.1819V19.5072C9.5 20.2189 10.2223 20.7028 10.8805 20.432L13.8805 19.1977C14.2553 19.0435 14.5 18.6783 14.5 18.273V13.8372C14.5 12.8089 14.8171 11.8056 15.408 10.964L19.8943 4.57465C20.3596 3.912 19.8856 3 19.0759 3Z" fill="black" />
                                    </svg>
                                </span>
                                Filter
                            </button>
                            <div class="menu menu-sub menu-sub-dropdown w-300px w-md-325px" data-kt-menu="true" id="kt-toolbar-filter">
                                <div class="px-7 py-5">
                                    <div class="fs-4 text-dark fw-bolder">Filter Options</div>
                                </div>
                                <div class="separator border-gray-200"></div>
                                <div class="px-7 py-5">
                                    <div class="mb-10">
                                        <label class="form-label fs-5 fw-bold mb-3">Month:</label>
                                        <select class="form-select form-select-solid fw-bolder" data-kt-select2="true" data-placeholder="Select option" data-allow-clear="true" data-kt-customer-table-filter="month" data-dropdown-parent="#kt-toolbar-filter">
                                            <option></option>
                                            <option value="dec">December</option>
                                        </select>
                                    </div>
                                    <div class="d-flex justify-content-end">
                                        <button type="reset" class="btn btn-light btn-active-light-primary me-2" data-kt-menu-dismiss="true" data-kt-customer-table-filter="reset">Reset</button>
                                        <button type="submit" class="btn btn-primary" data-kt-menu-dismiss="true" data-kt-customer-table-filter="filter">Apply</button>
                                    </div>
                                </div>
                            </div>
                            <button type="button" class="btn btn-light-primary me-3 d-none" data-bs-toggle="modal" data-bs-target="#kt_customers_export_modal">
                                <span class="svg-icon svg-icon-2">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                        <rect opacity="0.3" x="12.75" y="4.25" width="12" height="2" rx="1" transform="rotate(90 12.75 4.25)" fill="black" />
                                        <path d="M12.0573 6.11875L13.5203 7.87435C13.9121 8.34457 14.6232 8.37683 15.056 7.94401C15.4457 7.5543 15.4641 6.92836 15.0979 6.51643L12.4974 3.59084C12.0996 3.14332 11.4004 3.14332 11.0026 3.59084L8.40206 6.51643C8.0359 6.92836 8.0543 7.5543 8.44401 7.94401C8.87683 8.37683 9.58785 8.34458 9.9797 7.87435L11.4427 6.11875C11.6026 5.92684 11.8974 5.92684 12.0573 6.11875Z" fill="black" />
                                        <path d="M18.75 8.25H17.75C17.1977 8.25 16.75 8.69772 16.75 9.25C16.75 9.80228 17.1977 10.25 17.75 10.25C18.3023 10.25 18.75 10.6977 18.75 11.25V18.25C18.75 18.8023 18.3023 19.25 17.75 19.25H5.75C5.19772 19.25 4.75 18.8023 4.75 18.25V11.25C4.75 10.6977 5.19771 10.25 5.75 10.25C6.30229 10.25 6.75 9.80228 6.75 9.25C6.75 8.69772 6.30229 8.25 5.75 8.25H4.75C3.64543 8.25 2.75 9.14543 2.75 10.25V19.25C2.75 20.3546 3.64543 21.25 4.75 21.25H18.75C19.8546 21.25 20.75 20.3546 20.75 19.25V10.25C20.75 9.14543 19.8546 8.25 18.75 8.25Z" fill="#C4C4C4" />
                                    </svg>
                                </span>
                                Export
                            </button>
                            <a href="javascript:;" onclick="load_input('{{route('app.client.create')}}');" class="btn btn-primary">Tambah Data</a>
                        </div>
                        <div class="d-flex justify-content-end align-items-center d-none" data-kt-customer-table-toolbar="selected">
                            <div class="fw-bolder me-5">
                            <span class="me-2" data-kt-customer-table-select="selected_count"></span>Selected</div>
                            <button type="button" class="btn btn-danger" data-kt-customer-table-select="delete_selected">Delete Selected</button>
                        </div>
                    </div>
                </div>
                <div class="card-body pt-0">
                    <div class="table-responsive">
                        <div id="list_result"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="content_input"></div>
    @section('custom_js')
        <script type="text/javascript">
            load_list(1);
        </script>
    @endsection
</x-app-layout>